name: Code Quality Check
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on: [push]

jobs:
  server_lint:
    name: ESLint code style checks on server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm run server i

      - name: Lint code
        run: npm run server run lint

  server_build:
    name: Node v18
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create Server .env.test file
        run: |
          cd ./packages/server
          cp .env.test.example .env.test

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.9.0
        with:
          mongodb-version: '6.0'

      - name: Install Dependencies
        run: npm run server i

      - name: Check Types
        run: npm run server run check-types

      - name: Run Tests
        run: npm run server test
